#!/usr/bin/python


#This is my knocker

import socket
import logging
import sys
import argparse
import knocker_def as k_def
import struct
import time
import urllib2

parser=argparse.ArgumentParser(description="Knocker for CSC 574")
parser.add_argument("conf_file",help="Configuration file",metavar="Configuration_file",default="dummy_conf")
parser.add_argument("serverip",help="Ip Address of server",metavar="Ipaddress",default="dummy_ip")
parser.add_argument("-v","--verbose",help="Increased output verbosity",action="store_true")
parser.error=k_def.print_help

args=parser.parse_args()
if(k_def.error_check==True):
	print "Usage: ./knocker [-h] [-v] Configuration_file Ipaddress"
	print "Exiting"
	sys.exit()

if not args.verbose:
	logging.disable(logging.CRITICAL)

logger=logging.getLogger("Knocker")


logger.setLevel(logging.DEBUG)
ch=logging.StreamHandler()
formatter=logging.Formatter("%(name)s - %(levelname)s - %(message)s")
ch.setFormatter(formatter)
logger.addHandler(ch)
logger.debug("Logging is On")


conf_file=args.conf_file
ipaddress=args.serverip
print "Using Configuration File="+conf_file
print "Server IP="+ipaddress


try:
	s = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_RAW)
except socket.error, msg:
	print "Unable to create Socket"+ str(msg)
	sys.exit()

source_ip=socket.gethostbyname(socket.gethostname())
#source_ip="192.168.2.8"
dest_ip=ipaddress

try:
	port_sequence=[lines.rstrip('\n') for lines in open(conf_file,"r")]
except :
	print "Couldn't Open file"
	sys.exit()

logger.debug("port_sequence="+str(port_sequence))
seq_check=[port for port in port_sequence if not port.isdigit()]

if  seq_check :
	print "Error in port number"
	sys.exit()

range_check=[port for port in port_sequence if (int(port)<0 or int(port)>65535)]
if range_check:
	print "Check range of Port number"
	sys.exit()

ip_header=k_def.make_ip_header(source_ip,dest_ip)
seq_no=2000
for port in port_sequence:

	tcp_header=k_def.make_tcp_header(source_ip,dest_ip,seq_no,int(port))
	packet=ip_header+tcp_header
	s.sendto(packet,(dest_ip,0))
	print "Packet Sent,Seq_No=%s , Port=%s" %(str(seq_no),port)
	seq_no+=1
	time.sleep(0.4)

print "Knock Completed"
